model = ExtAPI.DataModel.Project.Model
pressure = model.Analyses[0].AddPressure() # Add a pressure.
part1 = model.Geometry.Children[0]  # Get the first part.
body1 = part1.Children[0]  # Get the first body.
face1 = body1.GetGeoBody().Faces[0]  # Get the first face of the body.
selection = ExtAPI.SelectionManager.CreateSelectionInfo(SelectionTypeEnum.GeometryEntities)  # Create an empty selection.
selection.Entities = [face1]  #  Add the face to the selection.
pressure.Location = selection  # Assign the selection to the pressure.
pressure.Magnitude.Inputs[0].DiscreteValues = [Quantity("0 [s]"), Quantity("1 [s]")]  # Set the time values.
pressure.Magnitude.Output.DiscreteValues = [Quantity("10 [Pa]"), Quantity("20 [Pa]")]  # Set the magnitudes.